# 设置变量
# redis
x-redis-image: &redis-image redis:6.2
x-redis-volumes: &redis-volumes
  - redis:/data 

# mysql
x-mysql-image: &mysql-image mysql:8.0
x-mysql-volumes: &mysql-volumes
  - mysql:/var/lib/mysql

# kylin
x-kylin-image: &kylin-image apachekylin/apache-kylin-standalone:4.0.0

# superset
x-superset-image: &superset-image liaozhiming/superset:2.0.0.202210

version: '3'
services:
  redis:
    image: *redis-image
    container_name: bi-redis-pro
    restart: unless-stopped
    networks:
      - bi
    environment:
      - TZ=Asia/Shanghai
    volumes: *redis-volumes

  mysql:
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
    image: *mysql-image
    container_name: bi-mysql-pro
    restart: unless-stopped
    ports:
      - 3306:3306
    networks:
      - bi
    # docker安全验证
    # security_opt:
    #   - seccomp:unconfined
    privileged: true
    environment:
      - MYSQL_DATABASE=superset
      - MYSQL_PASSWORD=superset
      - MYSQL_ROOT_PASSWORD=superset
      - MYSQL_USER=superset
      - TZ=Asia/Shanghai
    volumes: *mysql-volumes

  # 根据需要启动
  # cube; 能在亚秒内查询巨大的表;http://localhost:7070/kylin/login
  # 服务器配置至少16G
  # kylin:
  #   image: *kylin-image
  #   container_name: bi-kylin-pro
  #   restart: unless-stopped
  #   ports:
  #     - 7070:7070
  #     - 8088:8088
  #     - 50170:50070
  #     - 8032:8032
  #     - 8042:8042
  #     - 2181:2181
  #   networks:
  #     - bi
  #   environment:
  #     - TZ=Asia/Shanghai
  #   deploy:
  #     resources:
  #        limits:
  #           # cpus: "2.00"
  #           memory: 8G
  #        reservations:
  #           memory: 200M

  superset:
    image: *superset-image
    command: gunicorn --workers 10 -k gevent --worker-connections 1000 --limit-request-line 0 --limit-request-field_size 0 --timeout 120 --bind 0.0.0.0:8088 "superset.app:create_app()"
    container_name: bi-superset-pro
    restart: unless-stopped
    links:
      # - kylin:kylin
      - redis:redis
    depends_on:
      - mysql
      - redis
    environment:
      - MAPBOX_API_KEY=""
      - TZ=Asia/Shanghai
      - SECRET_KEY=\x1fLbg\xb2\xcfP\xef MJ8)\xb9\x04\x01\xf2&a\xbaG\x08<*\x13\xcd\x9bf\xd6\x82\xbf\xff
      - SQLALCHEMY_DATABASE_URI=mysql://superset:superset@mysql:3306/superset?charset=utf8mb4
    ports:
      - 8088:8088
    networks:
      - bi
    volumes:
      - ./superset/config.py:/app/superset/config.py

networks:
  bi:
    driver: bridge

volumes:
  mysql:
    name: data_bi_mysql
  redis:
    name: data_bi_redis
