name: Docker

on:   
  push:
    # # Publish `master` as Docker `latest` image.
    # branches:
    #   - main
    #   - develop

    # Publish `v1.2.3` tags as releases.二选一
    tags:
      - v*

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      # 检出代码
      - uses: actions/checkout@v3

      # 登录到dockerhub
      - name: Dockerhub login
        uses: docker/login-action@v1  # 三方的action操作,执行docker login
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # 抽取项目信息，主要是镜像的tag
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: liaozhiming/superset


      # 构建镜像并且推送到dockerhub
      - name: Build and push Docker image
        uses: docker/build-push-action@v2 # docker build & push
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILDTIME=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
            VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
            REVISION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}